### ISSUE TITLE
Node version compatibility

### ISSUE THREAD

**Issue by david-mears-2** [mrc-ide/mint#138]
I'm leaving this issue here in case it helps someone install in the future.

My `npm install` was failing (I think at the step of installing node-sass - the errors looked similar to [this](https://github.com/alphagov/govuk-prototype-kit/issues/984)), and I eventually found that downgrading my node version to 14 fixed it.

My npm version at the moment is 6.14.18, and my node version is now 14.21.3. The required node version should probably be added to the readme.

**Comment by plietar** [comment]
I've update to Node 20 in #142 and added the version to the README.
